spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serialzer: org.apache.kafka.common.serialization.StringSerializer